### ISSUE TITLE
Gene (NCBIGene:3643) <related_to> NamedThing <related_to> PhenotypicFeature (HP:0100750)

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#193]
**Query:** [insulinAtelectasis.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/insulinAtelectasis.json)
**PK:** [1c75694f-7cca-4a32-8cc3-5693715c43f5](https://arax.ncats.io/?r=1c75694f-7cca-4a32-8cc3-5693715c43f5)

At the Spring 2019 Hackathon at RENCI, on the "tidbits" focused on "Why is insulin associated with atelectasis?"
Google Drive:  https://drive.google.com/drive/folders/1_Qe9SzG5FanW35871qN3n9OkBqJNUhGC?usp=sharing 

We wanted to explore this tidbit in Translator 2022.  

![image](https://user-images.githubusercontent.com/38321826/165183113-85aee79a-1ee9-42c4-ac90-9d0350e94137.png)

**Comment by pg427** [comment]
As discussed during the Translator Standup, post running the query via the Explanatory Agent async endpoint,  the same six results were obtained (attached below). We are still looking to see if more results can be generated via async queries in general but at the moment, it seems both our dev instance and async query endpoint are displaying the same amount of results for this particular query.

![Screen Shot 2022-04-26](https://user-images.githubusercontent.com/58840680/165348143-75dbeeb7-7b2b-442f-8725-064f7f9584c7.PNG)

Link (xARA-async) :  https://explanatory-agent-dev.azurewebsites.net/v1.2/query_async/?uuid=2b0ee5b3-de8b-4e61-b47d-28e64f4f3219
