### ISSUE TITLE
Disease (MONDO:0004995) <has_manifestation> Pathological Process

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#198]
**Query:** [process.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/process.json)
**PK:** [48b08f7d-53d5-4929-a1dd-714380df436e](https://arax.ncats.io/?r=48b08f7d-53d5-4929-a1dd-714380df436e)

Exploring 'pathological_process' Entity type and how it is distinct from physiological process.

![image](https://user-images.githubusercontent.com/38321826/167492416-d4750829-5059-421c-9b16-7ab5b231b4d3.png)

**Comment by colleenXu** [comment]
@sstemann @MarkDWilliams The directionality of the title statement doesn't match the query here, which is confusing. 

The title implies that the query is MONDO:0004995 (cardiovascular disease, CVD) -(has_manifestation):arrow_right: PathologicalProcess, aka what are the manifestations of CVD?

But the query_graph file and ARAX link have an inverted subject/object....so the query is MONDO:0004995 :arrow_left:(has_manifestation)- PathologicalProcess, aka what stuff has CVD as a manifestation?

**Comment by colleenXu** [comment]
Also I think BTE will only have SEMMEDDB as a source with this predicate (manifestation) and semantic type (PathologicalProcess).
