### ISSUE TITLE
ChemicalEntity (PUBCHEM.COMPOUND:2083) <treats, disrupts, prevents, affects> Disease

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#200]
**Query:** [mayTreat.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/mayTreat.json)
**PK:** [40e8ecd2-da74-419d-9d3a-a18a57559986](https://arax.ncats.io/?r=40e8ecd2-da74-419d-9d3a-a18a57559986)

Looking for what disease Salbutamol "may treat"

![image](https://user-images.githubusercontent.com/38321826/168697465-d76dac1d-310d-409f-88a4-be279802bde5.png)

**Comment by colleenXu** [comment]
@sstemann @MarkDWilliams Something looks odd with this query: it looks like the subject/object have been inverted so it is basically asking "what diseases treat albuterol". This doesn't make sense. 

After switching the subject and object, the query is basically "what diseases are treated by albuterol". Then, BTE and others respond. 

https://arax.ncats.io/?r=21efda57-0c41-40e1-9d99-87db2d8244e0
![Screen Shot 2022-05-16 at 4 50 35 PM](https://user-images.githubusercontent.com/43731687/168700228-9cfd0df5-c5fb-4967-a543-0888b96647d2.png)

**Comment by sstemann** [comment]
thank you @colleenXu you are right!
