### ISSUE TITLE
Drug <treats> DiseaseOrPhenotypicFeature (MONDO:0018493) (malignant hyperthermia of anesthesia)

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#205]
**Query:** [Malignant_Hyperthermia_Treat.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/Malignant_Hyperthermia_Treat.json)
**PK:** [f304948c-99b0-4770-8e3b-bef16036947d](https://arax.ncats.io/?r=f304948c-99b0-4770-8e3b-bef16036947d)
**Control:** there's a single known treatment for Malignant hyperthermia, called Dantrolene

![image](https://user-images.githubusercontent.com/38321826/170769233-d42da598-027d-4ddd-95f6-5c0b12aeb1d4.png)

**Comment by andrewsu** [comment]
When the semantic type of `n01` is changed from `Drug` to `SmallMolecule`, more results are retrieved by BTE, including dantrolene https://arax.ncats.io/?r=9eef4e90-b94b-49e1-a483-38b72596f837

<details>
<summary>Query</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n01",
                    "object": "n00",
                    "predicates": [
                        "biolink:treats"
                    ]
                }
            },
            "nodes": {
                "n00": {
                   
                    "ids": [
                        "MONDO:0018493"
                    ],
                    "categories": [
                        "biolink:DiseaseOrPhenotypicFeature"
                    ]
                },
                "n01": {
                    "categories": [
                        "biolink:SmallMolecule"
                    ]
                }
            }
        }
    }
}
```
</details>

![image](https://user-images.githubusercontent.com/2635409/171223239-b9f17ebb-4ac5-43ab-808a-b49afa302b17.png)

![image](https://user-images.githubusercontent.com/2635409/171223716-bf9b951e-a9ad-4129-b138-a53a3206608d.png)

**Comment by sstemann** [comment]
seems to work in UI Test https://ui.test.transltr.io/main/results?l=Malignant%20Hyperthermia%20Of%20Anesthesia&i=MONDO:0018493&t=0&q=617dbf9b-2b27-44b0-8517-a68974e92d34
