### ISSUE TITLE
ChemicalEntity <ameliorates, affects> DiseaseOrPhenoTypicFeature (MONDO:0018078 - Soft Tissue Sarcoma)

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#208]
**Query:** [treats_softTissueSarcoma.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/treats_softTissueSarcoma.json)
**PK:** [94da86ce-520b-463c-a034-e638b1c6c905](https://arax.ncats.io/?r=94da86ce-520b-463c-a034-e638b1c6c905)

![image](https://user-images.githubusercontent.com/38321826/174353159-ef9d04da-7ef7-4e8d-bd80-adb53439a9dd.png)

**Comment by dkoslicki** [comment]
I don't know why ARAX is taking so long to respond when going through the ARS. Submitting to ARAX directly returns results quickly with no issue: https://arax.ncats.io/beta/?r=45391

**Comment by dkoslicki** [comment]
For those interested in results without SemMedDB (eg. @andrewsu ) here's an Operations & Workflow TRAPI message that filters them out:
```
{
  "workflow": [
    {
      "id": "fill"
    },
    {
      "id": "filter_kgraph_discrete_kedge_attribute",
      "parameters": {
        "edge_attribute": "biolink:knowledge_source",
        "remove_value": "infores:semmeddb"
      }
    },
    {
      "id": "overlay_compute_ngd",
      "parameters": {
        "virtual_relation_label": "N1",
        "qnode_keys": [
          "n0",
          "n1"
        ]
      }
    },
    {
      "id": "bind"
    },
    {
      "id": "complete_results"
    },
    {
      "id": "score"
    }
  ],
  "message": {
    "query_graph": {
      "edges": {
        "e0": {
          "subject": "n1",
          "object": "n0",
          "predicates": [
            "biolink:ameliorates",
            "biolink:affects"
          ]
        }
      },
      "nodes": {
        "n0": {
          "ids": [
            "MONDO:0018078"
          ],
          "is_set": false,
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ],
          "name": "MONDO:0018078"
        },
        "n1": {
          "is_set": false,
          "categories": [
            "biolink:ChemicalEntity"
          ]
        }
      }
    }
  },
  "submitter": "ARAX GUI",
  "stream_progress": true,
  "query_options": {
    "kp_timeout": "30",
    "prune_threshold": "50"
  }
}
```
With results here: https://arax.ncats.io/beta/?r=45393

**Comment by brettasmi** [comment]
imProving doesn't like this high-level CURIE, but it does support CURIEs of specific types of soft tissue sarcoma, e.g. angiosarcoma, epithelioid sarcoma, gastrointestinal stromal tumor:

```
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "ids": [
              "DOID:0001816",
              "DOID:6193",
              "DOID:9253"
            ],
          "categories": ["biolink:DiseaseOrPhenotypicFeature"]
        },
        "n1": {
          "categories": ["biolink:ChemicalEntity"]
        }
      },
      "edges": {
        "e0": {
          "subject": "n1",
          "object": "n0",
          "predicates": ["biolink:ameliorates", "biolink:affects"]
        }
      }
    }
  }
}
```

https://arax.ncats.io/?r=3cbb6c4f-1005-4cb8-a21e-e1d618b90043

**Comment by cbizon** [comment]
ARAGORN is also returning results when hit directly, not sure what's going on with the ARS/ARAGORN communication.

**Comment by sstemann** [comment]
@dkoslicki @cbizon this query was sent to the ITRB ARS Prod instance - do you want to verify your endpoint? https://ars-prod.transltr.io/ars/api/actors

**Comment by dkoslicki** [comment]
@sstemann POSTing the query to the endpoint listed in the ars actor for ARAX works as expected. So likely the issue lies at the ARS

**Comment by dkoslicki** [comment]
Mark W. has since fixed the issue with the ARS handling large responses, which led to it looking like ARAX was hanging. Removing team Expander tag

**Comment by sstemann** [comment]
https://ui.test.transltr.io/main/results?l=Soft%20Tissue%20Sarcoma&i=MONDO:0018078&t=0&q=c7ec23fb-e035-4e16-8a1f-cd11d73f3f9e
