### ISSUE TITLE
ChemicalEntity <ameliorates, affects> DiseaseOrPhenoTypicFeature (MONDO:0007114 - Angel-shaped phalango-epiphyseal dysplasia))

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#209]
**Query:** [dysplasia.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/dysplasia.json)
**PK:** [223e8ba3-4665-46c5-a00d-9fef355fb16f](https://arax.ncats.io/?r=223e8ba3-4665-46c5-a00d-9fef355fb16f)

This query was submitted to ars-prod (ITRB)

We also submitted the query to ars (free range) and @bill-baumgartner texting mining provided responded directly then.

![image](https://user-images.githubusercontent.com/38321826/175424650-484e8148-f059-46ed-934d-79d4c8386889.png)

**Comment by cbizon** [comment]
Seems as though aragorn was hung on some large queries when this ran.   We'll be keeping an eye on it to see if this is a recurring issue.  I reran it here: https://arax.ncats.io/?r=45fb8eb5-49bc-48eb-92ca-c4a4642ea490

The highest single chemical answer is pazopanib.   aragorn identifies a number of side effects common to treatment, plus common interactions with ABCB1 and ABCG2.

**Comment by sstemann** [comment]
https://ui.test.transltr.io/main/results?l=Angel-shaped%20Phalango-epiphyseal%20Dysplasia&i=MONDO:0007114&t=0&q=36469895-2bb8-48cb-a303-9a34085d9ba7
