### ISSUE TITLE
Inferred:  ChemicalEntity <ameliorates, treats, prevents, affects> DiseaseOrPhenotypicFeature (MONDO:0021783 - streptococcal sore throat)

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#212]
**Query:** [strepInferred.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/strepInferred.json)
**PK:** 
**Inferred multi-edges** [57ac203f-e7cf-4f7c-bfab-ad67cd8c4c89](https://arax.ncats.io/?r=57ac203f-e7cf-4f7c-bfab-ad67cd8c4c89)
**Inferred treats ONLY** [38ee4157-ac44-4727-b308-adf331e74354] (https://arax.ncats.io/?r=38ee4157-ac44-4727-b308-adf331e74354)
**non-Inferred, multi-predicates** [5a923a8-d783-4dd4-aefa-c2fa6009ca54] (https://arax.ncats.io/?r=c5a923a8-d783-4dd4-aefa-c2fa6009ca54)

This query was submitted to ars-prod (ITRB).  Added the treats predicate specifically based on update from Vlado re: MolPro/tree.

**Inferred multi-edges** 
![image](https://user-images.githubusercontent.com/38321826/176784017-4618fbd8-fafe-4d44-869e-94614ad82deb.png)

**Comment by colleenXu** [comment]
Noting that ARS-ITRB is probably hitting BTE's ITRB prod instance. None of BTE's ITRB instances have creative-mode, and they will ignore the "knowledge_type:inferred" part of the query and do a simple lookup (aka execute the query-graph). 

BTE's team has "creative-mode" on the non-ITRB development servers. However, the assumption has been that "creative-mode" queries have only 1 predicate in the query-edge.

**Comment by sstemann** [comment]
https://ui.test.transltr.io/main/results?l=Streptococcal%20Sore%20Throat&i=MONDO:0021783&t=0&q=b79287c4-da45-404e-9a2d-25e5529367de

we get results, theres some other weird stuff going on
