### ISSUE TITLE
QotM #4 What is the molecular target of SRI-37330?

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/testing#213]
**Background**: A cell assay screen for potential drug treatments for diabetes yielded a number of drugs with unknown targets. One candidate, SRI-37330, appeared to be beneficial in a murine model of diabetes and had an added benefit of improving fatty liver. Dr. Shalev has been unable to identify the exact target of the candidate (even after two years of in silico structural biology modeling) and cannot file a patent without one. See https://pubmed.ncbi.nlm.nih.gov/32726606/ for additional information.

_Important comment: In tackling this QotM, Translator team members should be mindful of intellectual property, given that Dr. Shalev is hoping to patent Drug X._

**Comment by colleenXu** [comment]
#206 err....isn't there another issue open for this?

**Comment by MarkDWilliams** [comment]
Whoops, this is indeed a duplicate
