### ISSUE TITLE
ChemicalEntity <ameliorates, treats, prevents, affects> DiseaseOrPhenotypicFeature (MONDO:0021668 - Pain)

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/testing#215]
**Query:** [pain.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/pain.json)
**PK:** [21e2cd1f-9e91-44c9-adf6-65bdd846f342](https://arax.ncats.io/?r=21e2cd1f-9e91-44c9-adf6-65bdd846f342)

This query was submitted to ars-prod (ITRB).  Added the treats predicate specifically based on update from Vlado re: MolPro/tree.

![Screen Shot 2022-07-11 at 2 41 20 PM](https://user-images.githubusercontent.com/12091335/178335254-d62abfa0-1b3c-41a3-b43b-d8613d46bcc2.png)

**Comment by dkoslicki** [comment]
@MarkDWilliams Was this to test the ITRB endpoints only? I noticed no `knowledge_type: inferred` property on the QG.

**Comment by sstemann** [comment]
this mondo is obsolete
