### ISSUE TITLE
Comparing creative mode: What chemical entity treats hypertension (MONDO:0005044) 

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#217]
**Query Regular:** [hyperTension.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/hyperTension.json)

**PK:**  [4e721a1c-954f-40f6-8fdf-1c5323c61646](https://arax.ncats.io/?r=4e721a1c-954f-40f6-8fdf-1c5323c61646)

**Query Inferred:** [hyperTensionInferred.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/hyperTensionInferred.json)

**PK:** [a2dfb8d5-b196-4308-9fd4-3ec510497169](https://arax.ncats.io/?r=a2dfb8d5-b196-4308-9fd4-3ec510497169)

![image](https://user-images.githubusercontent.com/38321826/179612885-6a5fa89a-3069-415c-8b7f-55c99cfa492b.png)

This query was submitted to ars-prod (ITRB).

**Comment by andrewsu** [comment]
on the inferred mode query, BTE quits with this error (based on our prior assumption that only `biolink:treats` would be sent).

```
{
    "code": null,
    "level": "WARNING", 
    "message": "Inferred Mode queries with multiple predicates are not supported. Your query terminates.",
    "timestamp": "2022-07-18T19:40:25.637Z"
}
```

I resubmitted the query with only `biolink:treats` as the predicate and got these results: https://arax.ncats.io/?r=ca8500b5-24c3-4159-9e5d-472f9eb55928

![image](https://user-images.githubusercontent.com/2635409/179789866-b8eb1dfc-067b-4497-b551-6151039a7f8b.png)

**Comment by sstemann** [comment]
works in Test UI https://ui.test.transltr.io/main/results?l=Hypertensive%20Disorder&i=MONDO:0005044&t=0&q=b97f53b2-6478-4ab4-bf4a-1f48e0ac06a8
