### ISSUE TITLE
Question of the Month #5: Psoriatic Arthritis

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/testing#220]
# Submitting Team

Multiomics EHR Risk Provider (Jenn H.)

## SME

**Philip Mease, MD, MACR,** received his undergraduate and medical degrees from Stanford University and completed a residency in internal medicine and a fellowship in rheumatology at the University of Washington. He cares for patients at Seattle Rheumatology Associates, directs the Rheumatology Research Division at Swedish Medical Center/Providence St. Joseph Health, and is Clinical Professor of Medicine at the University of Washington in Seattle. Dr. Mease’s research interests include psoriatic arthritis (PsA) and spondyloarthritis (SpA), rheumatoid arthritis (RA), and osteoarthritis (OA). His seminal 2000 Lancet paper established the efficacy of anti-TNF therapy in PsA. He has authored over 500 journal articles and numerous book chapters and has edited textbooks on PsA and SpA. Dr. Mease is past president and founding organizer of the Group for Research and Assessment of Psoriasis and Psoriatic Arthritis (GRAPPA), an international organization of over 800 rheumatology and dermatology researchers dedicated to research and education about psoriasis (PsO) and PsA. He is also an active member of the Assessment of Spondyloarthritis International Society (ASAS), the Spondyloarthritis Research and Treatment Network (SPARTAN), and the Outcome Measures in Rheumatology Clinical Trials (OMERACT) research organization. In addition, Dr. Mease is a Director of the Spondyloarthritis and Psoriatic Arthritis of the Consortium of Rheumatology Researchers of North America (CORRONA) and is co-chair of the PsA task force of the National Psoriasis Foundation, which in 2019 awarded him a lifetime achievement award for his work in advancing research on PsA.

## Challenge Question

*Simple question:* What are risk factors for progressing from PsO to PsA?

*Specific question:* In a population of patients with PsO, what risk factors could we use to recruit a cohort of patients with increased risk for new onset of PsA within three years?

## Background

The goals of this challenge question are to identify risk factors for new onset of PsA within three years among patients with PsO for the purpose of: (1) earlier recognition and treatment of PsA; and (2) recruitment of a cohort for a prospective multiomics study of pre-onset transition to PsA. In patients with PsO, known predictors of PsA include higher PsO severity, nail pitting, arthralgia, imaging-MSK inflammation, higher categories of BMI, family history, and select biomarkers. In addition, there are biomarkers associated with PsO severity and PsA severity. In outpatient-based cohort studies, the incidence rate of PsA per 100 patient-years varied from 1.34 to 17.4 ([Zabotti et al 2021](https://pubmed.ncbi.nlm.nih.gov/34596875/)). For prospective multiomics studies of transition to PsA, one would like an enriched population where at 25% to 50% of patients experience a transition. Screening for the study could include medical/exposome history, physical examination, standard of care clinical laboratory measures, or novel biomarkers. However, ideally, it would not require WGS or other more expensive or invasive assays at initial time of recruitment. Rather, WGS and other multiomics assays would be conducted on biobanked samples for patients who transition to PsA during a prospective trial.

Please see https://pubmed.ncbi.nlm.nih.gov/34385474/ for additional background.

Please post GitHub queries and results to this ticket.

## Additional Background (added August 5)

*Transition period from PsO to PsA*

- roughly 10 years
- symptoms progress slowly 

*Formal diagnosis of PsA*

- Caspar classification criteria
- PsA vs non-PsA inflammatory disorder
- evidence of inflammatory arthritis not osteoarthritis
- psoriasis plus negative Rheumatiod Factor
- psioriasis plus nail conditions, etc

*Prodromal phase*

- achiness, instability
- excessive fatigue
- scalp psoriasis
- psoriasis in folds of skin
- toe nail disease
- -omics markers suggested, e.g., TNF pathway, but tentative
- often misdiagnosed as fibromyalgia

## Timeline

**August 5, 2022** - First Friday of the Month Standup  
- Check-in/update from teams on progress

**August 12, 2022** - Second Friday of the Month Standup
- Check-in/update from teams on progress

**August 18, 2022** - Third Thursday of the Month Translator QotM mini-hackathon
- Review answers and refine queries with SME; wrap-up challenge

**August 26, 2022** - Fourth Friday of the Month 
- Translator QotM Challenge summary published in Gazette; next month's QotM Challenge announced

**Comment by jh111** [comment]
**Mondo**
Psoriasis (PsO): MONDO:0005083
Psoriatic arthritis (PsA): MONDO:0011849
psoriatic arthritis, susceptibility to, 1: MONDO:0100231
psoriatic arthritis, susceptibility to, 2: MONDO:0100232

**Sample query**

![image](https://user-images.githubusercontent.com/25163472/181645705-8ed915c6-0709-4e88-8f96-a7daf6a8f6b2.png)

```
{
  "edges": {
    "e0": {
      "object": "n0",
      "subject": "n1"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:PhenotypicFeature",
        "biolink:Disease"
      ],
      "ids": [
        "MONDO:0100231",
        "MONDO:0100232"
      ],
      "is_set": false
    },
    "n1": {
      "is_set": false
    }
  }
}


```

**Comment by Bassa1** [comment]
* PsA, MONDO:0011849, related to any disease:
![image](https://user-images.githubusercontent.com/100380537/181653921-de29a08a-f3e2-4ba5-9b56-296f790bb79e.png)

* Standard querying

`{
  "edges": {
    "e0": {
      "object": "n0",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n1"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:Disease"
      ],
      "ids": [
        "MONDO:0005083"
      ]
    },
    "n1": {
      "categories": [
        "biolink:Disease"
      ]
    }
  }
}`

[Arax result](https://arax.ncats.io/?r=40ae67f4-a4bb-4662-a222-b280f9430ef1)

**Comment by Bassa1** [comment]
![image](https://user-images.githubusercontent.com/100380537/183120930-e2fcf501-9d3e-456f-8de1-58ac5098a7aa.png)
 *Standard Query
`{
  "edges": {
    "e0": {
      "object": "n0",
      "predicates": [
        "biolink:developed_from"
      ],
      "subject": "n1"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:Disease"
      ],
      "ids": [
        "MONDO:0011849"
      ]
    },
    "n1": {
      "categories": [
        "biolink:Gene"
      ]
    }
  }
}`
[ARS Result](https://arax.ncats.io/?r=7be3d31b-2186-424f-aa85-82f5a6100b28)

**Comment by andrewsu** [comment]
Regarding this line in the background:
> In patients with PsO, known predictors of PsA include higher PsO severity, nail pitting, arthralgia, imaging-MSK inflammation, higher categories of BMI, family history, and select biomarkers.
Can we get a list of what those "select biomarkers" might be?  I'm guessing they are all in that review article, but I suspect an SME would do a much better job of extracting/summarizing that information than a non-SME...

**Comment by karafecho** [comment]
MONDO:0005083 (PsO)
PK = 880d7863-423c-4ed7-a032-f6c98cf7162c 

MONDO:0011849 (PsA)
PK = 77acf53d-d848-4984-917c-59eb59e4ff3c

```
{
  "edges": {
    "e0": {
      "object": "n1",
      "predicates": [
        "biolink:has_real_world_evidence_of_association_with"
      ],
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:Disease"
      ],
      "constraints": [],
      "ids": [
        "MONDO:0011849"
      ],
      "is_set": false
    },
    "n1": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "constraints": [],
      "is_set": false
    }
  }
}
```

**Comment by karafecho** [comment]
@jh111 @Bassa1 : I'm wondering if you all are planning to use the new Biolink predicate?

```
associated with
     correlated with
          positively correlated with
          negatively correlated with
     associated with likelihood of
```

**Comment by Bassa1** [comment]
@karafecho 
I am queering based on the new Biolink predicates

**Comment by Bassa1** [comment]
@karafecho @jh111 
I just chatted with Colleen about using the new Biolink predicates because I am not finding some of the predicates in the Translator. She said the ARAX. UI may not be updated to the bio link 2.4.8 version. I send a message on the UI slack channel

**Comment by jh111** [comment]
New resources available in the [QotM Psoriatic Arthritis directory](https://docs.google.com/document/d/1ikYD4g5IQ7xhM2XNgTxJPemwSg_njhRVb49M44WGXJ8/edit), including the CURIEs for known risk factors, additional queries, the Psoriatic Arthritis Primer and CASPAR criteria, and tracking SME questions for Dr. Mease @andrewsu

**Comment by marcdubybroad** [comment]
> However, ideally, it would not require WGS or other more expensive or invasive assays at initial time of recruitment. 
Would it make sense to use translator to cheaply fill out the genetic association picture at the start? It's putting the cart before the horse, but if we: 
- do a pso -> gene or pathway <- psa query
- find the top gene/pathway hits
- validate the data with the primer's expected genes/pathways (confidence in the translator results)
- use any new gene/pathway results to find what other phenotypes they are associated with
- look into those phenotypes as risk factors for pso leading to psa

**Comment by jh111** [comment]
@marcdubybroad Great suggestion. For the first steps we could also try
- PsO -> gene or pathway <- known PsA
- PsO -> gene or pathway <- medications used for PsA (but not PsO)

**Comment by marcdubybroad** [comment]
For the pso-pathway-psa query:
```
{
    "message": {
        "query_graph": {
            "edges": {
                "e0": {
                    "object": "pathway",
                    "subject": "pso"
                },
                "e1": {
                    "object": "psa",
                    "subject": "pathway"
                }
            },
            "nodes": {
                "pso": {
                    "categories": [
                        "biolink:PhenotypicFeature",
                        "biolink:Disease"
                    ],
                    "ids": [
                        "MONDO:0005083"
                    ],
                    "is_set": false
                },
                "psa": {
                    "categories": [
                        "biolink:PhenotypicFeature",
                        "biolink:Disease"
                    ],
                    "ids": [
                        "MONDO:0011849"
                    ],
                    "is_set": false
                },
                "pathway": {
                    "categories": [
                        "biolink:Pathway"
                    ],
                    "is_set": false
                }
            }
        }
    }
}
```
https://arax.ncats.io/?r=ae2b1e75-7eef-444f-a373-c199ff6e12c0
Note: we are in the process of loading about 300+ more pathway/phenotype associations, although we don't have pso/psa, but the results from linked pathways above could be used to query those phenotypes.

**Comment by Bassa1** [comment]
Thank you, Marc
This is great!  I queried with a single edge, but I haven't gotten results. Here is what I put in `PsO increases_degradation_of pathway correlated_with PSA`

**Comment by karafecho** [comment]
**Queries from 08.18.2022:**

https://arax.ncats.io/?r=8dddb496-127d-4fb8-951e-9047957d3fb3
https://arax.ncats.io/?r=a7ee2d96-2b73-4e01-b462-b978b19b0555
https://arax.ncats.io/?r=87bfe5ba-8d7c-4608-a04f-b3fcf4e0f3d6
https://arax.ncats.io/?r=609fe856-ae98-44a0-ba61-5b6dc325b90d
https://arax.ncats.io/?source=ARS&id=d2c0eea6-1a5a-4988-b90c-6049bfd82490
https://arax.ncats.io/?r=1994cac1-f36e-47a0-b67a-5b672aca0dfd
https://arax.ncats.io/?r=56948
https://arax.ncats.io/?r=56949
https://arax.ncats.io/?r=fe05df77-1f7e-4e1e-a422-26e1f429b787
https://uts.nlm.nih.gov/uts/umls/concept/C0009780
https://arax.ncats.io/?source=ARS&id=6fa04129-c12e-4c47-9975-8db33c81796a
https://arax.ncats.io/?r=4b834c60-29cd-452a-aa0a-ec9c3cc37dc3
https://arax.ncats.io/?r=457d390d-df3a-4d45-81e3-d3aa0bd8fbb6

**Comment by Bassa1** [comment]
@karafecho 
Thank you, Kara, for recording these queries. I added to the QotM [notes](https://docs.google.com/document/d/1ikYD4g5IQ7xhM2XNgTxJPemwSg_njhRVb49M44WGXJ8/edit)

**Comment by jh111** [comment]
[ARS query for Anything associated_with_increased_risk_for psoriatic arthritis](https://arax.ncats.io/?r=3b274f6c-1221-4cda-b742-8461a67ce105)

**Comment by karafecho** [comment]
Closing with comment in #233 ...
