### ISSUE TITLE
Comparing creative mode: What chemical entity treats chronic kidney disease (MONDO:0005300) 

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#225]
**Query Inferred/Creative:** [MVPckd.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/MVPckd.json)

**Inferred/Creative PK:**  [6c7631a8-9d45-41d8-8a9c-85f06d934ed0](https://arax.ncats.io/?r=6c7631a8-9d45-41d8-8a9c-85f06d934ed0)

**Query Standard:** [MVPckdSTD.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/MVPckdSTD.json)

**Standard PK:** [46673bfb-63e2-4054-9d6f-7dceffd8818c](https://arax.ncats.io/?r=46673bfb-63e2-4054-9d6f-7dceffd8818c)

These were run against ars-prod.  Inferred screenshot is on the left.
![image](https://user-images.githubusercontent.com/38321826/184702609-88cee1ca-4e4f-45d1-9a3f-a31c7161bdc6.png)

**Comment by sstemann** [comment]
@dkoslicki i did notice that if you run the MVP for a synonym of chronic kidney disease (such as end stage renal failure) ARAX does return in creative mode:  https://arax.ncats.io/?r=c5c0cc2a-1917-48f3-8507-a22ab40ca5fb

**Comment by cbizon** [comment]
We've been debugging ARAGORN, the version on staging handles this query fine (creative mode): https://arax.ncats.io/?r=873dfb75-8c36-4930-a6f1-3241b2fcd8bc

**Comment by dkoslicki** [comment]
That is interesting @sstemann , it appears that our model did not have MONDO:0005300, but does have MONDO:0004375, so this appears to be a synonym issue. I will post a ticket about it.

**Comment by cbizon** [comment]
There's a mix ( eg 2 & 3 are for 5300 ).  The diabetic kidney disease ones are because that is a subclass of chronic kidney disease, so KPs are responding with information about the subclass as we expect them to.   In the past we had decided not to explicitly relate those kinds of subclass results back to the input in the answer.  but maybe that's wrong in the context of the creative queries?

**Comment by sstemann** [comment]
looks to be working on UI Test:  https://ui.test.transltr.io/main/results?l=Chronic%20Kidney%20Disease&i=MONDO:0005300&t=0&q=5c7df930-6ea1-4eca-b5eb-1f29af78c1d3
