### ISSUE TITLE
Creative Mode MVP Hypertensive Nephropathy (MONDO:0024633)

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#226]
**Query Inferred/Creative:** [mvpHyperNephropathy.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/mvpHyperNephropathy.json)

**Inferred/Creative PK:**  [54e85d46-7f4f-4ab1-a59a-0b0e8e2309e9](https://arax.ncats.io/?r=54e85d46-7f4f-4ab1-a59a-0b0e8e2309e9)

**Query Standard:** [mvpHyperNephropathyStd.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/mvpHyperNephropathyStd.json)

**Standard PK:** [2a8180b3-cdd5-453f-adb1-8aa450f33911](https://arax.ncats.io/?r=2a8180b3-cdd5-453f-adb1-8aa450f33911)

These were run against ars-prod.  Inferred screenshot is on the left.
![image](https://user-images.githubusercontent.com/38321826/186022065-38bc5184-dc1e-413a-8754-d40fd62610bc.png)

**Comment by dkoslicki** [comment]
The fix for this synonymization issue is [awaiting deployment](https://github.com/RTXteam/RTX/issues/1891). In the meantime, here are the results from ARAX: https://arax.ncats.io/?r=59970

**Comment by pg427** [comment]
Explanatory Agent is currently setting up the latest versions on the ITRB servers. Once we have the latest database up and running on the servers, this issue should resolve automatically.

**Comment by Bassa1** [comment]
New Query:
Querying different entity and predicate:
`{
  "edges": {
    "e0": {
      "constraints": [],
      "knowledge_type": "inferred",
      "object": "n0",
      "predicates": [
        "biolink:associated_with_decreased_likelihood_of"
      ],
      "subject": "n1"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:Disease"
      ],
      "constraints": [],
      "ids": [
        "MONDO:0024633"
      ],
      "is_set": false,
      "name": "hypertensive nephropathy"
    },
    "n1": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "constraints": [],
      "is_set": false
    }
  }
}`

[ARS](https://arax.ncats.io/?r=f78542dc-281c-4f8a-9d90-46e825cc4e49)

**Comment by sstemann** [comment]
looks like three of four ARAs respond to this query in Test

https://arax.ncats.io/beta/?r=ef08031e-6145-4fdf-97f4-18f4e8e716d0
