### ISSUE TITLE
Unspecified nodes

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/testing#230]
One issue that arose during QotM no. 5, but has surfaced previously, is the challenge of unspecified nodes. In the August challenge, the issue became apparent with the queries below. Specifically, multi-hop queries with multiple unspecified nodes are challenging for Translator, even if anchored with two or more specified CURIEs.

enthesitis (MONDO:0044999) – gene – gene – gene – scalp disorder (MONDO:0024419): https://arax.ncats.io/?r=1994cac1-f36e-47a0-b67a-5b672aca0dfd

enthesitis (MONDO:0044999) – gene – gene – gene – scalp disorder (MONDO:0024419): https://arax.ncats.io/?r=56948

enthesitis (MONDO:0044999) – NamedThing – NamedThing – NamedThing – scalp disorder (MONDO:0024419):
https://arax.ncats.io/?r=56949

**Comment by gglusman** [comment]
(Note: 'entheritis' is a typo, should be 'enthesitis'.)

**Comment by karafecho** [comment]
Thanks for catching that (since corrected)!

**Comment by sstemann** [comment]
@karafecho what do we need to do here? it almost looks like an early pathfinder

**Comment by gglusman** [comment]
It does look similar as stated (phenotype 1, gene 1, gene 2, gene 3, phenotype 2), though my original query intent was to find candidate genes (gene 2) that regulated other genes (gene 1 and gene 3) that contributed to the two phenotypes.

**Comment by karafecho** [comment]
@sstemann : I created a ticket in the Feedback repo (https://github.com/NCATSTranslator/Feedback/issues/589) to suggest supporting pathfinding queries, and I cross-referenced this ticket, which I think can now be closed.
