### ISSUE TITLE
Creative Mode MVP Autism (MONDO:0005260) 

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#232]
**Query Inferred/Creative:** [mvpAutDis.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/mvpAutDis.json)

**Inferred/Creative PK:**  [a497f342-7ffa-437d-82a5-e5aa7fabe87a](https://arax.ncats.io/?r=a497f342-7ffa-437d-82a5-e5aa7fabe87a)

**Query Standard:** [mvpAutSTD.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/mvpAutSTD.json)

**Standard PK:** [12bd1c8e-a451-47b6-82c5-1c6eba854e9b](https://arax.ncats.io/?r=12bd1c8e-a451-47b6-82c5-1c6eba854e9b)

These were run against ars-prod.  Inferred screenshot is on the left.

![image](https://user-images.githubusercontent.com/38321826/188237320-2b5170ae-5875-4fcd-862d-8a4ef7bcbd1e.png)

**Comment by dkoslicki** [comment]
@sstemann Do you know what ARAX endpoint this was sent to? Running this just now did return results: https://arax.ncats.io/?r=63143

**Comment by dkoslicki** [comment]
@sstemann We're unable to reproduce this issue. I've submitted to https://ars-prod.transltr.io/ars/api/submit and we got results back https://arax.ncats.io/?r=76dd0fbc-c70d-4670-96a8-975c5220b51c

**Comment by sstemann** [comment]
looks like the ARAs respond to this in UI Test
