### ISSUE TITLE
WF Lookup: Gene <related_to> Disease (MONDO:0004975 - Alzheimer Disease)

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#234]
WF Query: [WFLookupAlz.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/WFLookupAlz.json)

PK: [f951d0c8-2a18-4655-9d52-08057aac46d8](https://arax.ncats.io/?r=f951d0c8-2a18-4655-9d52-08057aac46d8)

![image](https://user-images.githubusercontent.com/38321826/192395980-3f5f41f8-63ba-4cb4-90ed-6aa24f5b4d08.png)

tagging the ARA owners

**Comment by dkoslicki** [comment]
This appears to be a workflow runner issue (which is being looked into). Results from ARAX are to be expected since bypassing the WF runner gives: https://arax.ncats.io/?r=65751
