### ISSUE TITLE
MVP2 Candidate:  What proteins are physically interacting with CHEMBL1881825

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#237]
Query (standard): [proteinCHEMBL1881825.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/proteinCHEMBL1881825.json)

Results PK:  [5f879902-fc08-4bbc-a59b-ef8d54c93628](https://arax.ncats.io/?r=5f879902-fc08-4bbc-a59b-ef8d54c93628)

[UCWG Creative Mode Proposals #1](https://docs.google.com/spreadsheets/d/1gft4SdKRe6aLkRy9prZIP1lHyYvrLUmSKzQRouo7F2k/edit?usp=sharing)

[Feedback Issue #23](https://github.com/NCATSTranslator/Feedback/issues/23)

![image](https://user-images.githubusercontent.com/38321826/200409138-3fd2f450-cbb8-4e9a-a7b8-0b96a817a8b4.png)

**Comment by colleenXu** [comment]
(CC @andrewsu) We don't have any KPs that use that specific predicate; that's why we don't have any results.
