### ISSUE TITLE
MVP2 Qualified: What gene's activity or abundance is increased by a particular chemical (Zinc, PUBCHEM.COMPOUND:23994))?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#249]
**Query:** [mvp2dZinc.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/mvp2dZinc.json)
**PK:** [72895d13-60c5-497f-a635-a702c0b4d06f](https://arax.ncats.io/?r=72895d13-60c5-497f-a635-a702c0b4d06f)

This was run on ars,ci looking for KPs and ARAs that have updated their dev environments to support qualifiers in particular for the [MVP2 template query](https://github.com/NCATSTranslator/TranslatorArchitecture/issues/81) 

This compound of interest was initiated by NCATS user testing of the UI for disease [Phelan Mcdermid Syndrome (22q13.3 Deletion Syndrome](https://ui.transltr.io/results?q=e1450a50-76c9-45d8-87f0-63e53b8e6793)).  After reviewing results for Zinc connected to shank3, the user and Christine googled "zinc shank3" since there was no evidence on this part of the path in the UI (which is currently limited to pubmed) for MVP1.  Today's standard query with qualifiers, for zinc does show connections with evidence in the Translator network (whcibut not part of MVP1 evidence Zinc-shank3).

![image](https://user-images.githubusercontent.com/38321826/217084178-5fb6732a-04b8-481e-b426-72c6957df785.png)

**Comment by brettasmi** [comment]
This is a true 0 results from us, and not an implementation issue.

**Comment by andrewsu** [comment]
Apologies, this query has exposed an error in BTE's node normalization.  I will edit this post later to add more details.  In the mean time, this PK has perhaps more relevant results:

https://arax.ncats.io/?r=f74cf91f-3853-4961-b29e-b9966b2966a3

----

More notes:
The original query used `PUBCHEM.COMPOUND:23994` as the input ID.  Node normalizer (https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=PUBCHEM.COMPOUND:23994) returns two UMLS IDs (`UMLS:C0043481` and `UMLS:C0795680`), both of which should be used in queries by BTE.  It looks like the PK posted by Sarah ([72895d13-60c5-497f-a635-a702c0b4d06f](https://arax.ncats.io/?r=72895d13-60c5-497f-a635-a702c0b4d06f)) only used the latter UMLS ID.  The PK I posted above is when issuing the same query using the former UMLS ID.  The intended behavior is that BTE returns the union of those two PKs.  I have created an issue to track the fix: https://github.com/biothings/BioThings_Explorer_TRAPI/issues/560

**Comment by andrewsu** [comment]
I misdiagnosed the behavior above as a bug in BTE.  As noted by @tokebe in https://github.com/biothings/BioThings_Explorer_TRAPI/issues/560#issuecomment-1421281357, the issue was that the DEV Node Normalizer is returning the two UMLS IDs while the PROD Node Normalizer is returning one.  BTE is working as expected.  It's not obvious that this reflects a bug in Node Normalizer either, since probably either behavior can be justified based on different lumping/splitting criteria.

**Comment by sstemann** [comment]
cannot replicate on Test or Prod
