### ISSUE TITLE
duplicated entries in BTE results through ARS

### ISSUE THREAD

**Issue by andrewsu** [NCATSTranslator/testing#35]
I'm looking at the BTE results in response to the updated query for https://github.com/NCATSTranslator/testing/issues/33 (https://arax.ncats.io/?source=ARS&id=53afa7d0-861c-4033-897e-1efbfc6ab5fb), and I noticed that some of the BTE results are duplicated:

![image](https://user-images.githubusercontent.com/2635409/113434398-be79de00-9395-11eb-888c-c959a454cfe0.png)

Spot checking, it looks like the provenance of the edge is the same:

![image](https://user-images.githubusercontent.com/2635409/113434540-ff71f280-9395-11eb-9468-6f7756bbe337.png)

I don't see this duplication when executing the query against https://api.bte.ncats.io/v1/query/ directly.  I see 15 results when querying directly and 21 through the ARAX/ARS interface, so likely 6 of them are duplicated?  @MarkDWilliams can you help investigate if anything on the ARS end might explain this?

**Comment by sstemann** [comment]
@MarkDWilliams have you had a chance to take a look at this?

**Comment by colleenXu** [comment]
@andrewsu please close this since we have addressed this
