### ISSUE TITLE
RTX KG2: KP that doesn’t call other KP’s?

### ISSUE THREAD

**Issue by dkoslicki** [NCATSTranslator/testing#42]
I’m a bit confused about the layout of the repo: for the `onehop/templates` directory, there is an `ARA`  sub folder, of which RTX KG2 is listed in [this file](https://github.com/NCATSTranslator/testing/blob/main/onehop/templates/ARA/Expander_Agent/RTX_KG2.json). RTX/ARAX KG2 is a KP, not an ARA. Furthermore, since ARAX/KG2 is a KP itself, it does not call any other KP’s, so it appears that this file should be as follows:
```
{
    "url": "https://arax.ncats.io/kg2/api/rtxkg2/v1.0/ui/",
    "TRAPI": true,
    "KPs": []
}
```
Is this what was intended?

**Comment by cbizon** [comment]
Hmm, doesn't sound right.  The location and form of the template is based on the smart-api registration of the component.  So for KG2, this says:
```
  x-translator:
    component: ARA
    team: Expander Agent
```
so it's getting put in the ARA section.   My impression is that the component here is not about nature of the team,  but what kind of thing this API actually is.  So I would modify component here to be KP (this is what we've done for the automat services from ranking agent.)

Once that's done, then I can regenerate the templates and they should make a little more sense.

**Comment by dkoslicki** [comment]
Closing due to ARAX issue #1362 being closed
