### ISSUE TITLE
Removing labels from fixed issues: repo invite?

### ISSUE THREAD

**Issue by dkoslicki** [NCATSTranslator/testing#43]
Is there a possibility that I could be invited to this repo? The motivation is that we have fixed #20 and I’d like to be able to remove the `Expander` label from that for ease of tracking. I see Andrew Su was able to remove his team’s label, so assume it’s kosher to be added to the repo.

**Comment by sstemann** [comment]
@dkoslicki I added you and Stephen to the translator-standup Github group and added that group to this repo, it wasn't there before:

**Comment by dkoslicki** [comment]
Great, thanks! I’ll let you know if Andrew needs added anywhere (haven’t heard that he has).
